stages:
  - validate 
  - deploy
  - destroy

validate_job:
  stage: validate 
  tags:
    - shell
  script:
      - cd terraform
      - terraform init
      - terraform validate
  artifacts:
    paths:
      - CI_BUILDS_DIR 

deploy_job:
  stage: deploy
  tags:
    - shell
  script:
      - cd terraform
      - terraform apply -auto-approve
  only:
  - master
  artifacts:
    paths:
        - CI_BUILDS_DIR

destroy_job:
  stage: destroy
  tags:
    - shell
  script:
      - cd terraform
      - terraform destroy -auto-approve
  only:
  - master
  when: manual

 
