stages:
  - check 
  - plan
  - apply
  - destroy

variables:
  BRANCH_STATE_KEY: $AWS_STATE_KEY-$CI_COMMIT_BRANCH
        
fmt_job:
  stage: check 
  tags:
    - shell
  script:
      - terraform fmt -check -recursive terraform/

validate_job:
  stage: check 
  tags:
    - shell
  script:
      - cd terraform
      - terraform init -input=false -backend-config="bucket=$AWS_STATE_BUCKET" -backend-config="key=$BRANCH_STATE_KEY" -backend-config="region=$AWS_REGION"
      - terraform validate 

plan_job:
  stage: plan 
  tags:
    - shell
  script:
      - cd terraform
      - terraform init -input=false -backend-config="bucket=$AWS_STATE_BUCKET" -backend-config="key=$BRANCH_STATE_KEY" -backend-config="region=$AWS_REGION"
      - terraform plan -input=false -out "planfile"
  artifacts:
    paths:
      - terraform/planfile


apply_job:
  stage: apply
  tags:
    - shell
  script:
      - cd terraform
      - terraform init -input=false -backend-config="bucket=$AWS_STATE_BUCKET" -backend-config="key=$BRANCH_STATE_KEY" -backend-config="region=$AWS_REGION"
      - terraform apply -input=false -auto-approve "planfile"
  artifacts:
    paths:
      - ansible/inventory

destroy_job:
  stage: destroy
  tags:
    - shell
  script:
      - cd terraform
      - terraform init -input=false -backend-config="bucket=$AWS_STATE_BUCKET" -backend-config="key=$BRANCH_STATE_KEY" -backend-config="region=$AWS_REGION"
      - terraform destroy -input=false -auto-approve
  when: manual

 
