stages:
  - validate 
  - plan
  - apply
  - destroy

validate_job:
  stage: validate 
  tags:
    - shell
  script:
      - cd terraform
      - terraform init -backend-config="bucket=$AWS_STATE_BUCKET" -backend-config="key=$AWS_STATE_KEY" -backend-config="region=$AWS_REGION"
      - terraform validate

plan_job:
  stage: plan 
  tags:
    - shell
  script:
      - cd terraform
      - terraform init
      - terraform plan -out "planfile"
  artifacts:
    paths:
      - terraform/planfile


apply_job:
  stage: apply
  tags:
    - shell
  script:
      - cd terraform
      - terraform apply -auto-approve "planfile"
  when: manual

destroy_job:
  stage: destroy
  tags:
    - shell
  script:
      - cd terraform
      - terraform destroy -auto-approve
  when: manual

 
