stages:
  - validate 
  - deploy
  - destroy

validate_job:
  stage: validate 
  tags:
    - shell
  script:
      - cd terraform
      - terraform init
      - terraform validate
  artifacts:
    paths:
      - terraform/.terraform
      - terraform/.terraform.lock.hcl

deploy_job:
  stage: deploy
  tags:
    - shell
  script:
      - cd terraform
      - terraform apply -auto-approve
  artifacts:
    paths:
      - terraform/.terraform
      - terraform/.terraform.lock.hcl
      - terraform/terraform.tfstate

destroy_job:
  stage: destroy
  tags:
    - shell
  script:
      - cd terraform
      - terraform destroy -auto-approve
  when: manual

 
