stages:
  - validate 
  - deploy
  - destroy

validate_job:
  stage: validate 
  tags:
    - shell
  script:
      - cd terraform
      - terraform init
      - terraform validate
  artifacts:
    paths:
      - terraform/.terraform
      - terraform/.terraform.lock.hcl

deploy_job:
  stage: deploy
  tags:
    - shell
  script:
      - whoami
      - cd terraform
      - terraform apply
  only:
  - master
  artifacts:
    paths:
      - terraform/.terraform
      - terraform/.terraform.lock.hcl
      - terraform/terraform.tfstate

destroy_job:
  stage: destroy
  tags:
    - shell
  script:
      - cd terraform
      - terraform destroy
  only:
  - master
  when: manual

 
