stages:
  - validate 
  - deploy
  - destroy

validate_job:
  stage: validate 
  tags:
    - shell
  script:
          - cd terraform
          - terraform init
          - terraform validate
  cache:
    paths:
      - .terraform
      - terraform.tfstate

deploy_job:
  stage: deploy
  tags:
    - shell
  script:
          - ls -la
          - terraform apply
  only:
  - master
  cache:
    paths:
      - .terraform
      - terraform.tfstate

destroy_job:
  stage: destroy
  tags:
    - shell
  script:
          - terraform destroy
  only:
  - master
  when: manual
  cache:
    paths:
      - .terraform
      - terraform.tfstate

 
