stages:
  - init
  - validate 
  - deploy
  - destroy

init_job:
  stage: init
  tags:
    - shell
  script:
          - cd terraform
          - terraform init
  artifacts:
    paths:
            - output
  
validate_job:
  stage: validate
  tags:
    - shell
  script:
          - cd terraform
          - terraform validate
        
deploy_job:
  stage: deploy
  tags:
    - shell
  script:
          - cd terraform
          - terraform apply
  only:
  - master

destroy_job:
  stage: destroy
  tags:
    - shell
  script:
          - cd terraform
          - terraform destroy
  only:
  - master
  when: manual
  
