---
- name: "Copie des certificats et clés privés sur les workers"
  ansible.builtin.copy:
    src: "{{ item }}"    
    dest: ~/
  with_items:
    - "/tmp/certs/ca.pem"
    - "/tmp/certs/master-a-key.pem"
    - "/tmp/certs/master-a.pem"

- name: "Suppression des fichiers temporaires"
  shell: "rm -rf /tmp/certs"

