public_key_file         = "/home/vagrant/MlleC/ssh/id_rsa_aws.pub"
private_key_file        = "/home/vagrant/MlleC/ssh/id_rsa_aws"
database-name           = "mllec"
database-username       = "mllec"
database-password       = "alinuxien"
webserver-homepage-path = "/var/www/html"
domain                  = "mllec.akrour.fr"
website_title           = "MlleC"
website_admin           = "admin"
website_admin_pass      = "admin_pass"
website_admin_email     = "ali.akrour@gmail.com"

