---
- name: "Installation de CFSSL et CFSSLJSON"
  shell: "/usr/bin/find /usr/local/bin/cfssl -type f || wget https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson && chmod +x cfssl cfssljson && sudo mv cfssl cfssljson /usr/local/bin/"
