---
- name: "Copie des certificats et clés privés sur les workers"
  ansible.builtin.copy:
    src: "{{ item }}"    
    dest: "~/"
  with_items:
    - "/tmp/certs/ca.pem"
    - "/tmp/certs/worker-0-key.pem"
    - "/tmp/certs/worker-0.pem"
    - "/tmp/certs/worker-1-key.pem"
    - "/tmp/certs/worker-1.pem"

