---
- name: "Preparing encryption configuration temporary directory"
  ansible.builtin.file:
    path: /tmp/encryption
    state: directory

- name: "Creating Encryption Configuration Manifest"
  shell: 
    cmd: |
      cat > encryption-config.yaml <<EOF 
      kind: EncryptionConfig 
      apiVersion: v1 
      resources: 
        - resources: 
            - secrets 
          providers: 
            - aescbc: 
                keys:  
                  - name: key1 
                    secret: $(head -c 32 /dev/urandom | base64) 
            - identity: {} 
      EOF

- name: "Copying Encryption Configuration Manifest into temporary directory"
  ansible.builtin.copy:
    src: "encryption-config.yaml"
    dest: /tmp/encryption

